"""add nationality

Revision ID: eddd4fb0bf1b
Revises: d783a13523c9
Create Date: 2025-03-10 14:28:13.050877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eddd4fb0bf1b'
down_revision: Union[str, None] = 'd783a13523c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('nationality', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'nationality')
    # ### end Alembic commands ###
